dist: trusty
sudo: required
language: generic
env:
  - VER=4.1
  - VER=5.0
  - VER=5.1
before_install:
  - curl -s https://packagecloud.io/install/repositories/varnishcache/varnish${VER/./}/script.deb.sh | sudo bash
  - sudo apt-get install varnish=${VER}.*
script:
  - ./runtests.sh $VER
